import localFont from "next/font/local";
import "./globals.css";

const overwacht = localFont({
  src: "./fonts/big_noodle_titling.ttf",
  variable: "--font-overwacht",
  weight: "100 900",
})

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${overwacht.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
